#!/bin/bash

function icd(){
	# todo
	# -h help 
	# -s secret dirs 
	# icd ~$USER
	# check map files in ascending order
	# if locally dont use map (mounted link)
	# when mapping and $FOLLOW=FALSE dont map links
	# -l bug
	# make possible to icd .. 

HELPTEXT="USAGE: icd [-h|--help] [-v|--verbose] [-l|.|--local] [keyword]\n\n
\t-h|--help\tshow this help text and exit\n
\t-v|--verbose\tshow path of destination directory\n
\t-vv|--veryverbose\tdestination directory\n
\t-m|--map\tmap home filesystem and print to standard out and exit\n
\t-n|--nomap\tdo not use map for searching\n
\t-f|--follow\tfollow symbolic links (recommended for mapping)\n
\t-\t\tgo to previous directory\n
\t-l|.|--local\tstart search at current directory"

# PARSER + SET FLAGS
################################################################
POSITIONAL=()
VERBOSE=FALSE
VERYVERBOSE=FALSE
LOCAL=FALSE
MAPPING=FALSE
FOLLOW=""
START=~
DESTINATION=""
FOUND=""
USEMAP=TRUE
#HIDDEN="-not -path '*/\.*'"

while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
#		-s|--secret)
#			HIDDEN=""
#			shift # past argument
#			;;
		.|-l|--local)
			START=$(pwd)
			LOCAL=TRUE
			USEMAP=FALSE
			shift # past argument
			;;
		-f|--follow)
			FOLLOW=-L
			USEMAP=FALSE
			shift # past argument
			;;
		-m|--map)
			MAPPING=TRUE
			shift # past argument
			;;
		-n|--nomap)
			USEMAP=FALSE
			shift # past argument
			;;
		-v|--verbose)
			VERBOSE=TRUE
			shift # past argument
			;;
		-vv|--veryverbose)
			VERYVERBOSE=TRUE
			shift # past argument
			;;
		-)
			cd - && return 0;; 
		-h|--help)
			echo -e $HELPTEXT && return 0;; 
		*)    # unknown option
			POSITIONAL+=("$1") # save it in an array for later
			shift # past argument
			;;
	esac
	done
	set -- "${POSITIONAL[@]}" # restore positional parameters
	if [[ ${#POSITIONAL[@]} -gt 1 ]] 
	then 
		echo "Too many arguments!"
		echo -e $HELPTEXT
		return 0
	fi
	FINDARGUMENT=${POSITIONAL[0]}

# FIND DIR
################################################################
if [[ $MAPPING == TRUE ]]; then 
	echo "$( find $FOLLOW $START -not -path '*/\.*' -type d -iwholename "*${FINDARGUMENT%/}*")" 
else
	#CHECK MAP-FILES if not local or follow
#	if [[ $LOCAL == FALSE or $FOLLOW != "" ]]; then 
	if [[ $USEMAP == TRUE ]]; then 
		MAPRESULTS=$(grep -i $FINDARGUMENT $HOME/.icd/[0-9]* | awk '{print length, $0}' | sort -n | head -n1 | cut -d" " -f2- ) 
		FOUNDIN=${MAPRESULTS%:*}
		DESTINATION=${MAPRESULTS#*:}
	fi 

	if [[ $DESTINATION = "" ]]; then  
		#DESTINATION="$( find $FOLLOW $START $HIDDEN -type d \
		DESTINATION="$( find $FOLLOW $START -not -path '*/\.*' -type d \
			-iwholename "*${FINDARGUMENT%/}*" | \
			awk '{ print length, $0 }' | \
			sort -n | \
			cut -d" " -f2- | \
			head - -n 1 )"
			FOUNDIN="active search"
	fi	

	if [[ $VERBOSE = TRUE ]]; then
		echo "$DESTINATION"
	fi
	if [[ $VERYVERBOSE = TRUE ]]; then 
		echo "$DESTINATION found from $FOUNDIN"
	fi
	# CHANGE DIR	
	############################################################
	cd "$DESTINATION"
fi 
}

